{% set setup_py_data = load_setup_py_data() %}

package:
  name: dataclass-argparse
  version: {{ setup_py_data['version'] }}

source:
  path: ..

requirements:
  build:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    {% for dep in setup_py_data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}


build:
  noarch: python
  script:
        - python -m pip install --no-deps --ignore-installed .

test:
  imports:
    - dataclass_argparse
#  source_files:
#    - tests
#  requires:
#    {% for dep in setup_py_data['extras_require']['test'] %}
#    - {{ dep.lower() }}
#    {% endfor %}
#  commands:
#    - pytest .

about:
  home: https://github.com/fynnbe/dataclass_argparse
  summary: argparse with a type annotated namespace dataclass
  license: MIT
  license_file: LICENSE
